/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Department } from "./api/hospital-wl";
export { Department } from "./api/hospital-wl";
export namespace Components {
    interface TjmkMedbedApp {
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath": string;
        "departmentId": string;
    }
    interface TjmkMedbedReservationEditor {
        "apiBase": string;
        "departmentId": string;
        /**
          * @default []
         */
        "departments": Department[];
        "reservationId": string;
    }
    interface TjmkMedbedReservationList {
        "apiBase": string;
        /**
          * @default []
         */
        "departments": Department[];
    }
    interface TjmkMedbedStayEditor {
        "apiBase": string;
        "departmentId": string;
        /**
          * @default []
         */
        "departments": Department[];
        "stayId": string;
    }
    interface TjmkMedbedStayList {
        "apiBase": string;
        /**
          * @default []
         */
        "departments": Department[];
    }
}
export interface TjmkMedbedReservationEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTjmkMedbedReservationEditorElement;
}
export interface TjmkMedbedReservationListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTjmkMedbedReservationListElement;
}
export interface TjmkMedbedStayEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTjmkMedbedStayEditorElement;
}
export interface TjmkMedbedStayListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTjmkMedbedStayListElement;
}
declare global {
    interface HTMLTjmkMedbedAppElement extends Components.TjmkMedbedApp, HTMLStencilElement {
    }
    var HTMLTjmkMedbedAppElement: {
        prototype: HTMLTjmkMedbedAppElement;
        new (): HTMLTjmkMedbedAppElement;
    };
    interface HTMLTjmkMedbedReservationEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLTjmkMedbedReservationEditorElement extends Components.TjmkMedbedReservationEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTjmkMedbedReservationEditorElementEventMap>(type: K, listener: (this: HTMLTjmkMedbedReservationEditorElement, ev: TjmkMedbedReservationEditorCustomEvent<HTMLTjmkMedbedReservationEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTjmkMedbedReservationEditorElementEventMap>(type: K, listener: (this: HTMLTjmkMedbedReservationEditorElement, ev: TjmkMedbedReservationEditorCustomEvent<HTMLTjmkMedbedReservationEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTjmkMedbedReservationEditorElement: {
        prototype: HTMLTjmkMedbedReservationEditorElement;
        new (): HTMLTjmkMedbedReservationEditorElement;
    };
    interface HTMLTjmkMedbedReservationListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLTjmkMedbedReservationListElement extends Components.TjmkMedbedReservationList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTjmkMedbedReservationListElementEventMap>(type: K, listener: (this: HTMLTjmkMedbedReservationListElement, ev: TjmkMedbedReservationListCustomEvent<HTMLTjmkMedbedReservationListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTjmkMedbedReservationListElementEventMap>(type: K, listener: (this: HTMLTjmkMedbedReservationListElement, ev: TjmkMedbedReservationListCustomEvent<HTMLTjmkMedbedReservationListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTjmkMedbedReservationListElement: {
        prototype: HTMLTjmkMedbedReservationListElement;
        new (): HTMLTjmkMedbedReservationListElement;
    };
    interface HTMLTjmkMedbedStayEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLTjmkMedbedStayEditorElement extends Components.TjmkMedbedStayEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTjmkMedbedStayEditorElementEventMap>(type: K, listener: (this: HTMLTjmkMedbedStayEditorElement, ev: TjmkMedbedStayEditorCustomEvent<HTMLTjmkMedbedStayEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTjmkMedbedStayEditorElementEventMap>(type: K, listener: (this: HTMLTjmkMedbedStayEditorElement, ev: TjmkMedbedStayEditorCustomEvent<HTMLTjmkMedbedStayEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTjmkMedbedStayEditorElement: {
        prototype: HTMLTjmkMedbedStayEditorElement;
        new (): HTMLTjmkMedbedStayEditorElement;
    };
    interface HTMLTjmkMedbedStayListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLTjmkMedbedStayListElement extends Components.TjmkMedbedStayList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTjmkMedbedStayListElementEventMap>(type: K, listener: (this: HTMLTjmkMedbedStayListElement, ev: TjmkMedbedStayListCustomEvent<HTMLTjmkMedbedStayListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTjmkMedbedStayListElementEventMap>(type: K, listener: (this: HTMLTjmkMedbedStayListElement, ev: TjmkMedbedStayListCustomEvent<HTMLTjmkMedbedStayListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTjmkMedbedStayListElement: {
        prototype: HTMLTjmkMedbedStayListElement;
        new (): HTMLTjmkMedbedStayListElement;
    };
    interface HTMLElementTagNameMap {
        "tjmk-medbed-app": HTMLTjmkMedbedAppElement;
        "tjmk-medbed-reservation-editor": HTMLTjmkMedbedReservationEditorElement;
        "tjmk-medbed-reservation-list": HTMLTjmkMedbedReservationListElement;
        "tjmk-medbed-stay-editor": HTMLTjmkMedbedStayEditorElement;
        "tjmk-medbed-stay-list": HTMLTjmkMedbedStayListElement;
    }
}
declare namespace LocalJSX {
    interface TjmkMedbedApp {
        "apiBase"?: string;
        /**
          * @default ''
         */
        "basePath"?: string;
        "departmentId"?: string;
    }
    interface TjmkMedbedReservationEditor {
        "apiBase"?: string;
        "departmentId"?: string;
        /**
          * @default []
         */
        "departments"?: Department[];
        "onEditor-closed"?: (event: TjmkMedbedReservationEditorCustomEvent<string>) => void;
        "reservationId"?: string;
    }
    interface TjmkMedbedReservationList {
        "apiBase"?: string;
        /**
          * @default []
         */
        "departments"?: Department[];
        "onEntry-clicked"?: (event: TjmkMedbedReservationListCustomEvent<string>) => void;
    }
    interface TjmkMedbedStayEditor {
        "apiBase"?: string;
        "departmentId"?: string;
        /**
          * @default []
         */
        "departments"?: Department[];
        "onEditor-closed"?: (event: TjmkMedbedStayEditorCustomEvent<string>) => void;
        "stayId"?: string;
    }
    interface TjmkMedbedStayList {
        "apiBase"?: string;
        /**
          * @default []
         */
        "departments"?: Department[];
        "onEntry-clicked"?: (event: TjmkMedbedStayListCustomEvent<string>) => void;
    }

    interface TjmkMedbedAppAttributes {
        "basePath": string;
        "apiBase": string;
        "departmentId": string;
    }
    interface TjmkMedbedReservationEditorAttributes {
        "reservationId": string;
        "departmentId": string;
        "apiBase": string;
    }
    interface TjmkMedbedReservationListAttributes {
        "apiBase": string;
    }
    interface TjmkMedbedStayEditorAttributes {
        "stayId": string;
        "departmentId": string;
        "apiBase": string;
    }
    interface TjmkMedbedStayListAttributes {
        "apiBase": string;
    }

    interface IntrinsicElements {
        "tjmk-medbed-app": Omit<TjmkMedbedApp, keyof TjmkMedbedAppAttributes> & { [K in keyof TjmkMedbedApp & keyof TjmkMedbedAppAttributes]?: TjmkMedbedApp[K] } & { [K in keyof TjmkMedbedApp & keyof TjmkMedbedAppAttributes as `attr:${K}`]?: TjmkMedbedAppAttributes[K] } & { [K in keyof TjmkMedbedApp & keyof TjmkMedbedAppAttributes as `prop:${K}`]?: TjmkMedbedApp[K] };
        "tjmk-medbed-reservation-editor": Omit<TjmkMedbedReservationEditor, keyof TjmkMedbedReservationEditorAttributes> & { [K in keyof TjmkMedbedReservationEditor & keyof TjmkMedbedReservationEditorAttributes]?: TjmkMedbedReservationEditor[K] } & { [K in keyof TjmkMedbedReservationEditor & keyof TjmkMedbedReservationEditorAttributes as `attr:${K}`]?: TjmkMedbedReservationEditorAttributes[K] } & { [K in keyof TjmkMedbedReservationEditor & keyof TjmkMedbedReservationEditorAttributes as `prop:${K}`]?: TjmkMedbedReservationEditor[K] };
        "tjmk-medbed-reservation-list": Omit<TjmkMedbedReservationList, keyof TjmkMedbedReservationListAttributes> & { [K in keyof TjmkMedbedReservationList & keyof TjmkMedbedReservationListAttributes]?: TjmkMedbedReservationList[K] } & { [K in keyof TjmkMedbedReservationList & keyof TjmkMedbedReservationListAttributes as `attr:${K}`]?: TjmkMedbedReservationListAttributes[K] } & { [K in keyof TjmkMedbedReservationList & keyof TjmkMedbedReservationListAttributes as `prop:${K}`]?: TjmkMedbedReservationList[K] };
        "tjmk-medbed-stay-editor": Omit<TjmkMedbedStayEditor, keyof TjmkMedbedStayEditorAttributes> & { [K in keyof TjmkMedbedStayEditor & keyof TjmkMedbedStayEditorAttributes]?: TjmkMedbedStayEditor[K] } & { [K in keyof TjmkMedbedStayEditor & keyof TjmkMedbedStayEditorAttributes as `attr:${K}`]?: TjmkMedbedStayEditorAttributes[K] } & { [K in keyof TjmkMedbedStayEditor & keyof TjmkMedbedStayEditorAttributes as `prop:${K}`]?: TjmkMedbedStayEditor[K] };
        "tjmk-medbed-stay-list": Omit<TjmkMedbedStayList, keyof TjmkMedbedStayListAttributes> & { [K in keyof TjmkMedbedStayList & keyof TjmkMedbedStayListAttributes]?: TjmkMedbedStayList[K] } & { [K in keyof TjmkMedbedStayList & keyof TjmkMedbedStayListAttributes as `attr:${K}`]?: TjmkMedbedStayListAttributes[K] } & { [K in keyof TjmkMedbedStayList & keyof TjmkMedbedStayListAttributes as `prop:${K}`]?: TjmkMedbedStayList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tjmk-medbed-app": LocalJSX.IntrinsicElements["tjmk-medbed-app"] & JSXBase.HTMLAttributes<HTMLTjmkMedbedAppElement>;
            "tjmk-medbed-reservation-editor": LocalJSX.IntrinsicElements["tjmk-medbed-reservation-editor"] & JSXBase.HTMLAttributes<HTMLTjmkMedbedReservationEditorElement>;
            "tjmk-medbed-reservation-list": LocalJSX.IntrinsicElements["tjmk-medbed-reservation-list"] & JSXBase.HTMLAttributes<HTMLTjmkMedbedReservationListElement>;
            "tjmk-medbed-stay-editor": LocalJSX.IntrinsicElements["tjmk-medbed-stay-editor"] & JSXBase.HTMLAttributes<HTMLTjmkMedbedStayEditorElement>;
            "tjmk-medbed-stay-list": LocalJSX.IntrinsicElements["tjmk-medbed-stay-list"] & JSXBase.HTMLAttributes<HTMLTjmkMedbedStayListElement>;
        }
    }
}
