/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TjmkHospitalWlList {
    }
}
declare global {
    interface HTMLTjmkHospitalWlListElement extends Components.TjmkHospitalWlList, HTMLStencilElement {
    }
    var HTMLTjmkHospitalWlListElement: {
        prototype: HTMLTjmkHospitalWlListElement;
        new (): HTMLTjmkHospitalWlListElement;
    };
    interface HTMLElementTagNameMap {
        "tjmk-hospital-wl-list": HTMLTjmkHospitalWlListElement;
    }
}
declare namespace LocalJSX {
    interface TjmkHospitalWlList {
    }
    interface IntrinsicElements {
        "tjmk-hospital-wl-list": TjmkHospitalWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tjmk-hospital-wl-list": LocalJSX.IntrinsicElements["tjmk-hospital-wl-list"] & JSXBase.HTMLAttributes<HTMLTjmkHospitalWlListElement>;
        }
    }
}
